[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cession_bonding_curve = "HojxiDLyQPErBmdx6tiC3Hutn5iajPbBEZ14C568zTha"

[programs.localnet]
cession_bonding_curve = "HojxiDLyQPErBmdx6tiC3Hutn5iajPbBEZ14C568zTha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"
